from graph import Graph

import pprint

g6 = Graph()
node_list = list('abcdefghijk')
g6.add_edge(node_list[0], node_list[1], 1)
g6.add_edge(node_list[0], node_list[2], 2)
g6.add_edge(node_list[1], node_list[3], 3)
g6.add_edge(node_list[1], node_list[4], 4)
g6.add_edge(node_list[1], node_list[5], 5)
g6.add_edge(node_list[2], node_list[6], 6)
g6.add_edge(node_list[2], node_list[7], 7)
g6.add_edge(node_list[7], node_list[8], 8)
g6.add_edge(node_list[5], node_list[9], 9)
g6.add_node(node_list[10])
# g6.add_edge(node_list[9], node_list[10], 10)
btraversal = g6.breadth_first_traversal(node_list[0])
dtraversal = g6.depth_first_traversal(node_list[0])
print('\nTest #6 - Breadth')
print(btraversal)
print('\nTest #6 - Depth')
print(dtraversal)
print('\nTest #6 - Dijkstra')
pprint.pprint(g6.dijkstra(node_list[0], node_list[10]))
